version: '3'

services:

  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: del1al9
      MYSQL_DATABASE: Prueba
      MYSQL_USER: ulisest
      MYSQL_PASSWORD: del1al9
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  prueba_django:
    image: python:3.9.5
    container_name: prueba_djangoISDM
    restart: always
    volumes:
      - type: bind
        source: .
        target: /opt/back_end
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge